[package]
name = "rust-be-template"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
lazy_static = "1.4"
futures = "0.3"
log = "0.4"
env_logger = "0.10"